@echo off
cd /d "%~dp0"

rem ============================================================
rem  Project venv shell
rem  Generated by Venv Batch Template Generator v3.3
rem  Generated on: 2026-06-08 16:04
rem
rem  Opens an activated CMD session for this project.
rem  Use only when you need an interactive venv session.
rem  Exit with: exit
rem ============================================================

set "PROJECT_NAME=taxman"
set "VENV_DIR=.venv"
set "ACTIVATE=%CD%\%VENV_DIR%\Scripts\activate.bat"

if not exist "%ACTIVATE%" (
    echo [ERROR] Local venv was not found:
    echo         "%ACTIVATE%"
    echo.
    echo Create it with:
    echo         python -m venv "%VENV_DIR%"
    echo.
    pause
    exit /b 1
)

title "%PROJECT_NAME% - VENV SHELL"
call "%ACTIVATE%"

echo ============================================================
echo  Project shell activated
echo  Project: "%CD%"
echo  Python :
where python
echo  Type "exit" to leave this shell.
echo ============================================================
echo.
cmd /k
